ionos-cloud/dim

dim/dim/allocator.py
dim/dim/autodns3.py
dim/dim/errors.py
dim/dim/jsonrpc.py
dim/dim/models/dns.py
dim/dim/models/rights.py
dim/dim/models/util.py
dim/dim/rpc.py
dim/dim/rrtype.py
dim/dim/transaction.py
dim/requirements.txt

These are all the changes to bring DIM into the world of python3. It
fixes the incompatible changes from python2 to python3 and removes the
limits on the dependencies from requirements.txt.
It is important to note, that after this upgrade DIM will not work with Python2 anymore!

dim - bring DIM to Python3 world

---

dim/dim/dns.py
dim/dim/rpc.py

MySQL is very lenient when it comes to following the SQL standard. This
can result in wrong results when running select statements.
By enforcing stricter sql_mode these errors become apparant and can be
fixed.
Iin this case 4 group by clauses are fixed that are breaking when
setting the sql_mode to
REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
Some of the cases mentioned in #10 are not reproducible.

fixes #10 - fix group by clause for strict sql_mode

---

dim/dim/rpc.py

SQLAlchemy was complaining, that the columns could not be matched
without any help.
By adding explicit on clause column identifiers from the model
declaration (they do not match the column names in the database
sometimes) it stopped complaining.

fix #11 specify on clause

---

dim/dim/rpc.py

Reverts 1and1/dim#21 because it is incomplete.

Revert "dim - fix group by clause for zone views"

---

dimclient/README.md

Add a small README file to explain how to use dimclient.
This should help people to get started with the client library.

dimclient - provide a small README

---

.github/workflows/release_dim.yml
.github/workflows/release_ndcli.yml
dim/doc/_themes/rtd/theme.conf

This contains a couple fixes for the workflows of dim and ndcli to add the documentation and man pages, that were missing before.

add man pages and documentation

---

ndcli/dimcli/zoneimport.py

ndcli is able to import comments in zone files, which look like this:
foo A 127.0.0.1 ; a comment
WIth dnspython 2.1 an internal API changed and now the patch to
dnspython via ndcli doesn't work anymore.
We need to remove the monkey_patch to allow comment imports from zone files to make it possible to install ndcli with newer dnspython versions.

ndcli - remove comment import for zones

---

dim-testsuite/t/history-zone-dnssec
dim-testsuite/t/history-zone-group-root.t
dim-testsuite/t/history-zone-group.t
dim/dim/dns.py

This series of commits contains a number of fixes for test cases where the order was wrong.
It also fixes the random order when deleting RRs, which makes a couple test cases stable and avoids them resulting in errors.

Dim testsuite

---

dim-testsuite/t/history-zone.t

The test cases work without problems, but the order was all over the
place, which caused errors in the comparison.
WIth that fixed, this case now is okay.

dim-testsuite - fix testcase ordering

---

dim-testsuite/t/ipblock-show-1.t

This fixes the testcase, as the output order was wrong.

dim-testsuite - reorder testoutput

---

dim-testsuite/runtest.py
dim-testsuite/t/ipblock-show-1.t
dim-testsuite/t/ips-list-1.t
dim-testsuite/t/ips-list-2.t

Fix some more test cases.
This commit series also contains a fix in runtest.py to make Messages before the header work correctly.

Dim testsuite ipblock

---

dim-testsuite/t/rr-create-txt-1.t

There was no problem found in the code, just the ordering was wrong.

dim-testsuite - reorder test output

---

dim-testsuite/t/zone-view-list.t
dim-testsuite/t/zone-view-modify.t
dim-testsuite/t/zone-view-overlapping-rr.t
dim-testsuite/t/zone-view-show.t
dim-testsuite/t/zone-view-subzone.t
dim-testsuite/t/zone-view-with-arpa.t

Fix the test cases for zone views by reordering them.

dim-testsuite - fix zone view test cases

---

dim-testsuite/runtest.py
dim-testsuite/t/history-zone-root.t
dim-testsuite/t/layer3domain-ip-free.t
dim-testsuite/t/layer3domain-overlap-2.t
dim-testsuite/t/rrs-list-1.t
dim/dim/dns.py

These are more ordering issues found by running the testsuite.

dim-testsuite - fix more ordering issues

---

dim-testsuite/t/rr-create-aaaa-1.t
dim-testsuite/t/rr-create-cert-1.t
dim-testsuite/t/rr-create-from-pool-2.t
dim-testsuite/t/rr-create-srv-1.t
dim-testsuite/t/rr-delete-2.t
dim-testsuite/t/rr-delete-3.t

The file rr-delete-3.t was completely broken. No idea what was going on
there, but nothing in that file worked.
Somehow zone was replaced with test everywhere, which broke most ndcli
commands and the resulting test output.

dim-testsuite - fix more test case files

---

dim-web/cas/login.py

This fixes two small issues in dim-web to make it work with more recent
python3 versions.

dim-web - fix python2 incompatibility

---

dim/dim/ldap_sync.py
dim/manage_dim

add dry-run parameter, and additional log output
ldap_sync:
* decode username to string
* add log output for sync_departments
* add log output for uid changes in sync_users
* add dry-run parameters
manage_dim:
* add dry-run parameter for ldap sync commands

improve ldap sync

---

dimclient/dimclient/__init__.py

per default, flask refreshes cookies for permanent sessions:
https://flask.palletsprojects.com/en/2.0.x/config/#SESSION_REFRESH_EACH_REQUEST
update dimclient's cookie file with refreshed cookie(s) from the DIM's response
tested for ndcli; (other) scripts using the login_prompt function will
keep their cookies fresh with this change

dimclient: refresh cookie file from session

---

dim/app.py
dim/dim/ldap_auth.py
dim/dim/ldap_sync.py
dim/requirements.txt

As mentioned in #166 python-ldap is currently causing problems on recent
systems with an updated libldap.
This is a first try to get the system migrated to the pure python ldap
library ldap3.
As I do not have a test system, this should be carefully considered and
tested before usage.
If anyone is willing to make this work, please take over this pull request :)

dim - migrate to ldap3

---

dim-testsuite/runtest.py

This allows to run the `dim-testsuite` on Python 3.6, which does not support `list` in type hints.
* switch to `typing` module's `List`
* fix data types

dim-testsuite: support running on python3.6

---

dim/dim/rpc.py
dimclient/dimclient/__init__.py

make `get_username()` verify that the rpc user is in DIM,
and have `DimClient` check that for `logged_in` instead
of `/index.html`

dim/dimclient: detect missing user

---

.gitignore
dim-testsuite/Makefile

install local code with editable flag set, so the virtual env does not have
to get recreated or be manually updated on code changes.
https://pip.pypa.io/en/stable/cli/pip_install/?highlight=editable#editable-installs
also add testsuite-related folders to `.gitingore`

dim-testsuite: use editable install

---

dim/dim/__init__.py
dim/dim/rpc.py

* remove function that's only relevant for Python 2.7,
which is not supported anymore
* reformat using `black --skip-string-normalization`
* removed unused imports
* `exc_info` should be bool, not int

remove legacy Python 2.7 code

---

dim-testsuite/runtest.py
dim-testsuite/t/container-list.t
dim-testsuite/t/container_move_layer3domain.t
dim/dim/models/ip.py

Single IPs were dropped from the output when using list containers.

dim - return /32 or /128 single available IPs

---

dim-testsuite/Makefile
dim-testsuite/runtest.py
dim/dim/__init__.py
dim/dim/manage_db.py
dim/dim/manage_dim.py
dim/dim/report.py
dim/manage_db
dim/manage_dim
dim/report
dim/requirements.txt
dim/setup.py

as Flask-Script is deprecated, switch to click
see https://github.com/smurfix/flask-script/issues/179
Bump flask and jinja to supported versions
Current deviation from the old scripts:
* does not support `-t` => can probably be worked around by setting the parameter directly,
e.g `FLASK_APP='dim:create_app(db_mode="TEST")' flask db clear`
resolves #82

use click instead of flask-script

---

.github/workflows/release_dim.yml
VM-SETUP.md
dim/CHANGES
dim/dim/version.py
dim/doc/administrator.rst
dim/doc/api.rst
dim/doc/conf.py
dim/doc/dimclient.rst
dim/doc/index.rst
ndcli/dimcli/version.py
ndcli/doc/conf.py

Update documentation:
* Document Python version requirements for DIM and dimclient/ndcli
* Add new API calls
* Update extended/changed API calls
* add `graphviz` for the `release_dim` action as sphinx needs to render graphs, e.g. in `dim/doc/ip.rst`
* bump versions
for #223

Update documentation for 5.0 release

---

ndcli/dimcli/__init__.py

use layer3domain from `.ndclirc` for ndcli commands where possible
resolves #236

ndcli: use l3d from .ndclirc for more command

---

dim/dim/manage_db.py

In this context .hex is not a function.

dim - .hex is not a function

---

.github/workflows/run_tests.yml
dim-testsuite/Makefile

add automated pytests on push
this should make it easier to merge changes
also add parameters to use custom pdns databases in the tests (eventually)

add automated tests

---

.github/workflows/run_tests.yml

run tests for pull requests in addition to pushes
follow-up to #244

run test action for pull requests

---

dim/requirements.txt

bump dependencies to their most recent versions

bump dependencies for dim

---

dim/CHANGES
dim/dim/version.py
dim/doc/conf.py
ndcli/CHANGES
ndcli/dimcli/version.py
ndcli/doc/conf.py

Update CHANGES and version files in preparation for 5.0.2 release.

dim,ndcli - update to 5.0.2

---

dimclient/dimclient/__init__.py

By default `urllib.request.open` uses the global socket timeout which is None (no timeout)

Add request timeout parameter

---

dim/dim/commands.py
dim/dim/manage_dim.py
dim/dim/rpc.py

add command to delete users from DIM
so there's at least one way to do that,
without using the db directly
resolves #257

add delete user command to manage_dim

---

dimclient/README.md

As discussed with @Srudush here's a short summary on how to install the dim client with PIP from github.

Info on how to use requirements.txt with github

---

ndcli/README.md

Document installation in a pip3 venv

---

dim/dim/ldap_sync.py
dim/dim/manage_dim.py

add command to add a user from LDAP, so they can be added to groups for permissions

manage_dim: add subcommand to add user from LDAP

---

dim/dim/models/migrate.py

replace deprecated `pkg_resources` with `importlib.resources` according to the migration guide
https://importlib-resources.readthedocs.io/en/latest/migration.html
resolves deprecation warning:
```
/opt/dim/lib64/python3.9/site-packages/dim/models/migrate.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
import pkg_resources
```

dim/models: replace deprecated pkg_resources
