ionos-cloud/dim

dim/requirements.txt

This brings flask at least a bit to a newer version without major
problems.
This solves the same problems as #1, #2 and #3 but also updates Jinja2 as a requirement for Flask 1.0.

update flask dependencies

---

ndcli/doc/gendoc.py
ndcli/requirements.txt

The man page was incomplete due to issues in gendoc.py
I've also updated the dependency dnspython to the latest version, i think version 1.12.0 from 2014 was just not compatible with python3.

Fix some minor python3 issues for ndcli

---

ndcli/dimcli/__init__.py
ndcli/requirements.txt
ndcli/setup.py

As the version string wasn't updated in some time, we should fix it.
According to
https://packaging.python.org/guides/single-sourcing-package-version/
this is the way to go.

ndcli - fix version string returned by ndcli

---

dim/dim/__init__.py
dim/dim/jsonrpc.py

It happens every now and then, that cookies are being denied by the
SecureCookieSession, but we do not get a reason.
In these cases, an abort was sent, which resulted in unhandled output
and then stack traces and crashes in python handlers.
Now these error cases get reported in the same json style and should
lead to less problems on the client side.
It was tested with the available ndcli and instead of crashing it will
report the error and return a proper exit code.

fix error handling for invalid cookies

---

dim/dim/rrtype.py

This is the correct solution according to
https://docs.python.org/3.0/whatsnew/3.0.html
> The builtin basestring abstract type was removed. Use str instead. The
str and bytes types don’t have functionality enough in common to warrant
a shared base class. The 2to3 tool (see below) replaces every occurrence
of basestring with str.
This fixes #19

dim - replace basestring with str

---

dim/dim/rpc.py

The Zoneview subquery was grouping by the zoneview id column. This would
lead to every view being counted as one.
The aim of the query was to count the views for each zone, which means
the group by needs to be on the zone_id.
Fixes #18

dim - fix group by clause for zone views

---

dimclient/dimclient.py
dimclient/setup.py

This removes `six` as a dependency from dimclient. This removes the dependency on python2 completely for dimclient, but might not be enough to make ndcli purely work with python3 without six.

Remove six for dimclient

---

dim/requirements.txt

Current dim relies on the six package for a couple functions. As long as
these exist in the code, we need to keep the six dependency.
It was removed in d4d1294 as porting everything to python3 was ongoing.

dim - add six dependency

---

.github/workflows/release_ndcli.yml

This adds the fedora build for dimclient (necessary for ndcli) and removes the obsolete release_build workflow, which is not needed anymore.

ndcli - add fedora to release workflow

---

.github/workflows/release_ndcli.yml

The release process had some problems with the correct name of the
packages.
This also fixes a missing variable.

ndcli - fix release process

---

dim/dim/models/ip.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

This makes it possible to list custom attributes when listing pools.
The `list pools` command got a new flag `-a` or `--attributes`, the same
as with list ips, which takes a list of attributes to return.
The API endpoint ippools_list got the new parameter attributes, which
takes the list of fields to return.

add custom attributes to output of list pools

---

.github/workflows/release_dim_web.yml
dim-web/cas.wsgi
dim-web/setup.py

This finalizes the dim-web packaging and makes the package available for CentOS7, 8 and debian.
The package is done as a pure python package, but needs a prebuild step to build the node.js stuff.
The frontend stuff is put into /usr/share/dim-web/www, so that it can be published via a webserver.
What doesn't work is to change the configuration, as it is hardpackaged into the resulting javascript file. The build process didn't age that well too, so unless someone knows how to extract the config file from the package, sed will need to be used as a replacement.

ready dim-web packaging

---

.github/workflows/release_dim.yml

Somehow we ended up not packaging our dim but something from python
hosts.
The cause is that the relative directory operator was missing, which
caused this behavior.
*This is an import fix, as we are currently shipping the wrong thing!*

workflow - release dim needs a fix

---

dim/dim/rpc.py

When introducing the -a option to select pool attributes in
2462524 a new parameter attributes was
added to ippool_list with the default being None.
This causes a problem with older clients. Attributes is tried to be
iterated over when it is checked against the reserved keywords.
But older clients do not send the attribute parameter, which causes it
to be None and therefore causing
ERROR - 'NoneType' object is not iterable
When we switch the default to being an empty list, the output will be as
before and even older clients can get the same output.

dim - fix compatibility with older ndcli clients

---

dim-testsuite/t/pool-list-2.t
dim/dim/models/ip.py
dim/dim/rpc.py

This implementes the missing tests for #48.
When the user managed attribut list for pools was implemented it was
tested with the default field list (vlan, name), subnets and custom
attributes, but never with the standard attributes.
Needless to say, they didn't work, because they were never selected in
the query and therefore were always empty.
This commit fixes that situation and at the same time adds the missing
tests.

dim - fix pool list with attributes

---

dim-testsuite/README.md

This should help to run specific testcases, that might cause problems
instead of always running them all and having to wait.

dim-testsuite - add explanation on how to run a test

---

dim-testsuite/t/ip-free-1.t
dim-testsuite/t/ip-free-3.t
dim/dim/dns.py

When an IP was freed, the order for deleting RR records not
deterministic. Now it is and therefore the result in case of errors is
more predictable.

dim-testsuite, dim - fix delete order

---

dim-testsuite/t/layer3domain-ip-free.t
dim-testsuite/t/layer3domain-list-ips.t
dim-testsuite/t/layer3domain-overlap-2.t
dim-testsuite/t/layer3domain-overlap-3.t
dim-testsuite/t/layer3domain-remove-subnet.t
dim-testsuite/t/layer3domain-rr-list.t
dim/dim/models/history.py

This fixes all the testcases for layer3domain. It was mostly some
reordering and a small fix in the history handling for pools.
We may need to revisit that part, but for now, it should work.

dim-testsuite - fix layer3domain tests

---

dim-testsuite/t/output-create-pdns-db.t
dim-testsuite/t/output-modify.t

This removes some trailing whitespaces, fixes a typo and reorders two
test cases to make them work.

dim-testsuite - fix output tests

---

dim-testsuite/runtest.py
dim-testsuite/t/rr-delete-1.t
dim/dim/allocator.py

When the IPv6 split was computed the datatype changed to float. This
caused the loss of the smallest bits because of how float was
implemented.
Using integer division this problem was partially circumvented. But then
the addition of two IPv6 addresses as integers will cause the result to
be of type long. This is a problem as integer division doesn't seem to be
implemented for long. The result was always 0, but didn't cause a type
error.
This means we needed to change the formula a bit, to run the calculation
with smaller numbers.

dim - fix allocator for ipv6

---

dim/dim/rpc.py

We have jsut hit the problem, that older clients may not sent an
attribute list. This resulted in an empty list to be returned.
To avoid this problem, we need to set the old default, so that older
clients still receive the proper list.

dim - modify default argument for attribute list

---

dim/dim/rpc.py

This fixes an issue with older clients, that didn't sent the attribute list. With the new default values, older clients can be used a bit longer.

fix argument list for list pools

---

dim/requirements.txt

Pin the dependencies the avoid problems because of random dependency
updates.
The two most important updates in the last couple weeks are SQLALchemy
and Flask, which are currently breaking dim.

dim - pin dependencies

---

dim/dim/allocator.py

In python2 a division between two integers always ended up being an
integer.
In python3 this was changed to result in floats.
To revert back to the old behaviour use integer division or floor
division as its called in python.

dim - fix allocator ending up with floats

---

dim-testsuite/runtest.py
dim/dim/models/dns.py
ndcli/dimcli/cliparse.py

Ensure compatibility with Debian 9 (which ships with Python 3.5):
* use `.format()` instead of `f""`
f-strings were added in 3.6 and are not supported in earlier versions
https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498
While adjusting the code,I noticed one statement used the wrong variable:
* fix error message for type mismatch of rdata (models/dns)

do not use f-strings

---

dim/dim/dns.py

Add a check if the user has permission to delete the IP deleted as part
of the RR.
As a deletion can cascade to other records and subnets, we need to check
each and everyone of them.
Fixes #88

dim - when deleting RR check permissions on IPs

---

packaging/RPM/pdns-output/.gitignore
packaging/RPM/pdns-output/SOURCES/pdns-output.properties
packaging/RPM/pdns-output/SOURCES/pdns-output.service
packaging/RPM/pdns-output/pdns-output.spec

related to #71
steps to build
```
cd packaging/RPM/pdns-output
_version="4.0.0";  tar --transform="s,^dim/,dim-${_version}/," -czvf ./SOURCES/dim-${_version}.tar.gz  ${dim_source_dir}
rpmbuild --define="_topdir $(pwd)" -bs pdns-output.spec
mock -vr epel-8-x86_64 --enable-network --rebuild ./SRPMS/pdns-output-4.0.0-1.src.rpm
```

RPM spec file for pdns-output

---

dim/doc/jsonrpc.rst

update example cookie with current name etc.
random cookie returned by dim-vm
this should be less confusing for devs/users of the json-rpc interface

update session cookie in docs

---

dim-testsuite/t/layer3domain-create.t
dim/dim/rpc.py

Now instead of a SQL error a custom error message pointing to the actual
problem is raised.
This fixes #120

adjust error message when deleting a layer3domain

---

dim-testsuite/t/container-layer3domain.t
ndcli/dimcli/__init__.py

Add keyword 'all' to layer3domain of 'list containers' to view all
containers in all layer3domains. It is still possible to view only the
containers of a single layer3domain.
Fixes #125

add option to view all containers in all layer3domains

---

ndcli/dimcli/__init__.py

This allows the user to set a default layer3domain name to use for all requests.
If necessary the layer3domain can still be changed on a per request basis.
fixes #117

set the default layer3domain in ndclirc

---

dim-testsuite/Makefile
dim-testsuite/runtest.py
ndcli/dimcli/__init__.py

By adding environment variables NDCLI_USERNAME and NDCLI_SERVER ndcli
can not be configured to use other servers or usernames via environment
variables too.
NDCLI_COOKIEPATH was also added if the cookie path for the same user
needs to be adjusted.
The default cookiepath was changed from ~/.ndcli.cookie to
~/.ndcli.cookie.{ username }.
Cookies are already stored per hostname in the cookie store, but there
is no distinction between different usernames. Therefore it was possible
that for a different user the same cookie was used.
By changing the default, each username now gets its own cookie store and
mix ups do not happen anymore.
There is the drawback for people who test with many different users,
thay they will accumulate many different files now.
Another problem is, that this change …

ndcli,dim-testsuite: add support for NDCLI_USERNAME and NDCLI_SERVER

---

dim-testsuite/t/layer3domain-create.t
dim-testsuite/t/layer3domain-modify-type.t
dim/dim/rpc.py
ndcli/dimcli/__init__.py

This adds the functionality to modify a layer3domain. The type can be
any string as it was until now.
The route distinguisher value is kept as is and when changing back to
vrf can still be set.
This should fix #119

allow modifying the type of layer3domains

---

dim-testsuite/t/layer3domain-create.t
dim/dim/rpc.py

Fixes #165
Do not allow layer3domain 'all' because it is used as a keyword in the
API to return all layer3domains.

dim - do not allow layer3domain called all

---

dim/dim/ldap_auth.py
dim/dim/ldap_sync.py

This makes LDAP Authentication and Sync work again with ldap3, see #166 / #167
* `()` is not a valid filter in ldap3, require a proper one for query()
* specify attributes we want from LDAP for easier access
* support setting TLS parameters for the LDAP connection from the config file
* add minimal typing
Allowing custom TLS parameters to support e.g. disabling verification in development
environments, or using a specific certificate file to verify against.

fix ldap_sync and ldap_auth for ldap3

---

dimclient/dimclient/__init__.py

previous call would try to evaluate the user input (username),
fix to just use Python 3's `input()` and use its prompt
resolves #174

dimclient: fix username prompt on Python 3

---

dim/dim/defaults.py
dim/dim/ldap_sync.py
dim/manage_dim

Use dry-run functionality provided by [dim/transaction.py#91](https://github.com/1and1/dim/blob/6a4b7d9d3cdaa39d95e29ae31c557b533e268a10/dim/dim/transaction.py#L91) instead of `if`s in `ldap_sync.py`
Add thresholds for deletions to catch cases like misconfiguration and issues with the LDAP server.
resolves #89

use transaction wrapper's dryrun for dim/ldap_sync and add deletion thresholds

---

dim-testsuite/t/group-pools.t
dim/dim/rpc.py
ndcli/dimcli/__init__.py

Fixes #138 
This adds a new command line option to set and unset the owning group on pools.
We should maybe deprecate the old command line flag. If we do, how should that be done? Only in documentation or also with a debug message?

Pool owning group

---

dim-testsuite/Makefile
ndcli/dimcli/__init__.py
ndcli/doc/man.rst

For debugging it is a hindrance to pull in the default `~/.ndclirc` as
it might contain overrides for some variables.
To avoid the problem a new environment variable NDCLI_CONFIG is defined
to point ndcli somewhere else for the config. This is also the default
for running the tests and can be overriden with the same environment
variable.
This would also allow users to have multiple configs for each
layer3domain they are using and prepare them as aliases, for example
```
alias ndcli_orgA=NDCLI_CONFIG=~/.ndclirc_orgA ndcli
alias ndcli_orgB=NDCLI_CONFIG=~/.ndclirc_orgB ndcli
```

ndcli - allow override of ndclirc

---

ndcli/dimcli/__init__.py

The config path can be loaded from an environment variable. But with
this change came a typo in the path, which lead to the ndclirc not being
found by default.

ndcli - fix default config path

---

dim-testsuite/Makefile
dim-testsuite/runtest.py

Adjust the testsuite's `Makefile` to use the `pdns` user and credentials from the documentation instead of `root`.
Also create the log directory within `make test`, to make sure it's there, even when `make install`, `make db` and `make test` are run separately.
Set `stdout` to a file handle of the logfile instead of passing the path as string, as that's what `Popen()` requires.
Set `stderr` to `subprocess.STDOUT` to make it use the same file (handle).

fix logging and make db for the testsuite

---

dim-testsuite/Makefile
dim-testsuite/README.md
dim-testsuite/runtest.py

allow running specific tests via `make test` so they can be checked
more easily
adjust the diff output to only compare failed tests, which compares fewer
files
e.g. this hides with tests that are ok, but differ in things that the
testsuite itself ignores, like timestamps
add special handling for meld,
to only run one instance comparing all failed tests
update documentation to reflect recent changes, for e.g. logging

dim-testsuite: allow running single test

---

dim-testsuite/Makefile
dim/dim/__init__.py
dim/requirements-dev.txt
dim/requirements.txt
ndcli/requirements-dev.txt

* add more reusable targets and add some dependencies
* add a separate target for editable pip install
* add target for pytest
* stricter requirements for deps
Adding a separate target for the editable pip install,
as that causes issues with e.g. read-only bind mounts
of the code in containers, as editable install adds
files to the *source* tree.
Adding the `pytest` suite to run the unit tests,
add default `LAYER3DOMAIN_WHITELIST` when running
with `testing` enabled, so the `pytest` tests can run.
Specifying stricter versions so `pip` can resolve the
dependencies in a timely fashion.
It complained
```This is taking longer than usual.
You might need to provide the dependency resolver
with stricter constraints to reduce runtime.
```
and would not complete within 15 minutes.

dim-testsuite: add more make targets

---

dim-testsuite/t/container_move_layer3domain.t
dim/dim/models/history.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

fixes #124
Add the API and ndcli command to move a container to a new layer3domain.
All static entries directly underneath the container will be moved to
too. All other entries (subnets, reserved IPs, ...) will be kept und
attached to the parent container.
When no parent container exists the action will be aborted as it would
break the assumption that a subnet has a parent.

add API to move container to layer3domain

---

dim-testsuite/t/pool_change_layer3domain.t
dim/dim/models/history.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

Add functionality to move a pool to another layer3domain. With the move
all subnets all entries therein are moved as well.
All reverse entries are moved from heir current view to their new view
(named after the layer3domain by default).
Fixes #123

Pool set layer3domain

---

dim-testsuite/t/history-layer3domain.t
dim/dim/rpc.py
ndcli/dimcli/__init__.py

This adds the layer3domain option to `history ipblock` to limit the
history to a specific layer3domain.
Before it could happen that the history of the same IP or Prefix from
different layer3domains was shown.

allow filtering for layer3domains for history ipblock

---

dim/dim/__init__.py
dim/dim/ipaddr.py
dim/dim/jsonrpc.py
dim/dim/models/dns.py
dim/dim/rpc.py
dim/dim/rrtype.py
dim/requirements.txt

Remove dependency on  the `six` module, which was left over from the Python 2/3 compat.
resolves #176

remove dependency on six

---

dim/dim/models/rights.py

>DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0
https://docs.python.org/3/library/inspect.html#inspect.getargspec
Use drop-in replacement `getfullargspec()`

replace deprecated getargspec function

---

dim/dim/commands.py
dim/dim/ipaddr.py
dim/dim/models/ip.py

this should make the results in the report more correct,
* floor `current_free`
* ceil used ips
make sure the numbers in the report are integers, see #198

pool_report: floor/ceil to int

---

dim/dim/rpc.py

make order for reference records returned by `rr_get_references()`
persistent/predictable by sorting them by their `id` attribute
this makes `RRReferencesTest::test_get_references` work, see #198

order rr references by id

---

dim/dim/rpc.py

expose layer3domain as parameter for `ippool_count()` and pass it on, to allow filtering by layer3domain
this fixes a regression introduced in #193, which added a new required parameter to `_ippool_query()`:
`FAILED tests/pool_test.py::PoolTest::test_list_ippools_pagination - TypeError: RPC._ippool_query() missing 1 required positional argument: 'layer3domain'`

rpc/ippool_count: support layer3domain

---

dim-testsuite/t/pool-list-4.t
dim-testsuite/tests/util.py
dim/dim/models/ip.py

adjust the db model for `Pool` to return the list of subnets
sorted by priority, which prohbably is what a user expects in general
additionally, fix the test function `assertDictSubset()` to make sure msg is a string,
as it would sometimes fail, see #198
resolves #168

list pool: order subnets by priority

---

dim/dim/rpc.py

`as_scalar()` has been replaced with `scalar_subquery()` in
SQLAlchemy 1.4:
https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.scalar_subquery
> Query.scalar_subquery() method replaces the Query.as_scalar() method.

deprecation: replace as_scalar()

---

dim/requirements.txt
ndcli/requirements.txt

dnspython breaks at least the zone import tests in `zone-import-arpa.t`, fails with `ERROR - add() has non-origin SOA`
see https://github.com/rthalley/dnspython/issues/766
the upstream fix should make it into 2.2.1

do not use dnspython 2.2.0

---

dim-testsuite/t/rr-create-txt-2.t
dim-testsuite/tests/dns_test.py

adjust expected output to current ndcli behaviour/order
add pytests for txt record splitting
relates to #72

fix rr-create-txt-2

---

dim-testsuite/t/rights-same-group.t
dim/dim/models/rights.py

Fixes #171
A user had to be in different groups to receive network and dns
permissions.
With this change a user can be in a single group and receive network and
dns permissions.
This should also work for groups in departments. As these can't be
created via DIM, this can not be tested though.

dim - allow network and dns permissions on same group

---

dim-testsuite/t/container-autocorrect.t
dim-testsuite/t/container-layer3domain.t
dim-testsuite/t/container-list-2.t
dim-testsuite/t/container-list.t
dim/dim/models/ip.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

extend list containers to support listing containers
for all layer3domains
also take user's configured layer3domain into account, via `get_layer3domain()`
always print the layer3domain for `ndcli list containers` to avoid confusion with the output as the user can configure the layer3domain in various places (environment variable, config), that don't show up in the command-line.
only print the layer3domain (name) if it actually has containers

ndcli: allow listing containers in all layer3domains

---

dim-testsuite/t/rr-create-mx-1.t
dim-testsuite/t/rr-create-mx-3.t
dim/dim/dns.py
dim/dim/models/dns.py
dim/dim/rrtype.py

To allow NULL MX records it was necessary to extend the validate_args
method with the context of other fields.
According to RFC7505 a preference of 0 is allowed when the target is
only '.' and the same in the other direction.
That means that both fields need to be checked in such cases which
requires the context of the other field.
In the future this allows us to implement similar validations for other
record types.
Fixes #128

dim - allow NULL MX records (RFC7505)

---

.github/workflows/release_dim.yml
.github/workflows/release_dim_web.yml

disable build-id links for rpms as that results in file conflicts
with our virtual environments in `/opt`
bump Python version required for dim-web to 3.9:
* use `python39` via appstream for el8
* use virtual-env now, as dependencies are not packaged upstream/in epel
* rename package and add corresponding obsoletes/provides

update actions for dim-web

---

dim/dim/ldap_sync.py
dim/dim/rpc.py

fix filters for cases where a user-group has a department, ldap3 expects filters to
adhere to https://datatracker.ietf.org/doc/html/rfc4515
(in brackets)
resolves issues creating user-groups that have a department from ldap,
and the ldap sync if such groups are present

fix filters for ldap3

---

.github/workflows/release_dimclient.yml
.github/workflows/release_ndcli.yml

install git/tar to make sure checkout works in actions on el8
`oraclelinux:8` comes without tar/git by default, but either of those is required to get the git checkout via `actions/checkout@v2`.

actions/el8: make sure checkout works

---

dim-testsuite/t/history-layer3domain.t
dim/dim/rpc.py
ndcli/dimcli/__init__.py

fix regression introduced in #188:
make layer3domain parameter for `history_ipblock()` optional so it works with older versions of ndcli
additionally:
* use user's configured layer3domain for `ndcli history ipblock` by default
* add support for `all` keyword  as value for layer3domain to show history from all l3ds for both `ndcli history ipblock` and `ndcli history layer3domain` commands

add support for showing history from all layer3domains

---

dim-testsuite/tests/allocator_test.py
dim/requirements-dev.txt

mark error tracked in #205 as known failure,
this allows us to check for passing pytest,
in e.g. actions
see https://docs.pytest.org/en/7.1.x/how-to/skipping.html
also bump pytest, and remove dependency on click in dev

mark bug as known failure

---

dim-testsuite/t/pool_change_layer3domain.t
dim/dim/rpc.py

When detecting collisions for the moved subnets it was also checked if
maybe possibly a subnet exists just before the moved subnet which
reaches into the subnet.
Which is just wrong. With this fix the checks look correct.

dim - fix collision detection when moving between layer3domains

---

.github/workflows/release_ndcli.yml
packaging/debian/ndcli/debian/control

add `bash-completion` as a weak dependency for the ndcli packages
adding as weak dependency to not depend on `bash` itself
resolves #226

ndcli: add weak dependency on bash-completion

---

ndcli/doc/gendoc.py

make `gendoc` add its parent directory to `sys.path` instead of `..`,
so the current working directory does not have to be ndcli/doc
this reduces the complexity of building the documentation for packaging etc,
as we don't have to change directories

ndcli/doc: improve gendoc path

---

dim-testsuite/tests/ipblock_test.py
dim/dim/rpc.py

fix permission check by passing the layer3domain as well as pool,
as it's possible to set either for `ip_free()`
add pytest to verify it's working with multiple layer3domains

rpc: fix freeing free ip

---

dim-testsuite/t/pool-set-attrs.t
dim/dim/models/rights.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

Extend the permission system with a new permission to allow network
admins to grant the permission to set attributes on pools.
The permission is bound to a prefix so that attributes can be
namespaced and assigned to different groups for usage.

dim,ndcli - add new permission to set attributes on pools

---

dim/dim/rpc.py

This can lead to errors when MySQL is configured to require all columns
in the group by clause.

dim - fix missing columns in group by clause

---

dim-testsuite/t/pool-modify-layer3domain.t
dim-testsuite/t/pool_change_layer3domain.t
dim/dim/rpc.py

The function _delete_reverse_zones expected the subnet to be deleted
already. This lead to many reverse zones not being deleted or the
transaction being blocked altogether.
By forcing the deletion and working with a copy of the actual Subnet
object the deletion now goes through without problems.
Fixes #233

dim - better cleanup when moving pools with small subnets

---

dim-testsuite/t/pool-modify-layer3domain.t
dim/dim/rpc.py

It wasn't checked if the pool was already in layer3domain and therefore
printed some messages that resulted from that fact.

dim - check if pool is already in layer3domain

---

dim-testsuite/tests/dns_test.py
dim/dim/rpc.py
ndcli/dimcli/__init__.py

When zone-profiles are copied to become a real zone, the A and AAAA
records must belong to layer3domain.
It is not feasible to specify on the layer3domain each A/AAAA record
needs to go to when ndcli create zone is executed.
To avoid this problem, zone-profiles must not contain A or AAAA records.

fix #238 - do not allow A/AAAA/PTR records in zone-profiles

---

dim/dim/ldap_sync.py
dim/dim/manage_dim.py

it's currently possible to manually add users
to groups that are being synced from ldap,
this adds an option/flag for ldap sync,
that allows removing manually added users from such groups

add option to clean up user-groups from LDAP

---

VM-SETUP.md

The syntax for setting user type has changed (from i think version 4 to 5)

The syntax for setting user type has changed

---

ndcli/dimcli/__init__.py

I want to create records with a configurable default TTL (specified in the .ndclirc file) without having to change the global TTL of the zone.
Therefore, this Pull Request implements a new option named `default-ttl` in the .ndclirc file. Specifying this option results in setting the `ttl` for created resource records if not specified otherwise while creating the record.
For example, specifying `default-ttl = 300` in the config and creating a new record with `ndcli create rr example.com. a 1.2.3.4` would result in specifying the TTL just like creating the record with `ndcli create rr example.com. ttl 300 a 1.2.3.4`.
It is still possible to specify a different TTL while creating the record by explicitly providing the TTL like before (i.e. `ndcli create rr example.com. ttl 60 1.2.3.4`).
Not …

Allow to configure default TTL for created records using .ndclirc

---

dimclient/dimclient/__init__.py
dimclient/dimclient/version.py
dimclient/pyproject.toml

disable strict checking of the DIM server certificate, as verify fails with `Basic Constraints of CA cert not marked critical` otherwise
tested as working in Python 3.9 with http/https, and Python 3.13 with https
see also https://github.com/kovidgoyal/calibre/commit/cb1bfb98a0680c1495c503a846c6b810861e2d95
resolves #284

dimclient: work around issues due to SSL defaults changes in Python 3.13

---

ndcli/dimcli/zoneimport.py

The problem of following cases on importing a new zone solved.
Before patch:
```
$ cat <<EOF | ndcli import zone dlan.legacy.test
; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.10.rc1.el6_3.6 <<>> axfr dlan.legacy.test @anyins-ins-bs01.dlan.legacy.test
;; global options: +cmd
dlan.legacy.test.        3600    IN      SOA     ins01.internal.test. dnsadmin.company.com. 2005110840 600 180 604800 3600
dlan.legacy.test.        3600    IN      NS      ins01.internal.test.
dlan.legacy.test.        3600    IN      NS      ins02.internal.test.
1021931729._dkimkey.dlan.legacy.test. 300 IN TXT "v=DKIM1\;k=rsa\;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCFpZEaLQAbzDDMkmDMZNzulKNI9QWcGOtD9SaMPwJ48xHRfTUxW1AIUgH/i1gFg0uM988hcNSyljkK81p0ASDGTmRBEwDZrHE+G96XOUhi4OZppteMswbbuDy3AIXQB/JG5ktFl0eYdAejkucOG0uIlvpeNhrSNn2wjASg …
```

fix(dim/ndcli): issue of adding TXT records fixed on importing zone.
